version: '3.9'

services:

  app:
    container_name: app
    image: hyperf/hyperf:8.0-alpine-v3.13-swoole
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    volumes:
      - ./backend:/app
    ports:
      - 9501:9501
    depends_on:
      - db
      - redis
    networks:
      - bubble

  db:
    container_name: db
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "secret"
    networks:
      - bubble

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6378:6379
    networks:
      - bubble

networks:
  bubble:
    external: true